---
title: "Lab 00 - Hello IDS!"
author: "Daniel Livingston"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Peter Rabbit", "Bosh", "Daniel", 
           "Pierce", "Jakob"),
  github_username = c("mcgregors-garden", "username 1", "username 2", 
                      "username 3", "username 4"), 
  colour = c("powderblue", "magenta", "aquamarine", 
             "lawngreen", "yellow"),
  hobby = c("Hopping", "Jumping", "Running", 
            "Walking", "Flying"),
  favourite_number = c(2, 2, 2, 2, 2)
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```


### Exercises 19

Change the text of the plot title and axis labels.

```{r labelled-bar-plot}
p1 + labs(x = "Username", 
          y = "Number",
          title = "Insert text here")
```

### Exercise 20

```{r new-bar-plot}
p2 <- ggplot(team_data, aes(x = hobby)) +
  geom_bar()
p2
```

